services:
  abstract:
    build:
      context: ./Docker
      dockerfile: Dockerfile
      args: 
        - IMAGE_NAME=abstract
    image: abstract:latest
    ports:
      - 3333:80
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb
    networks:
      - mvc-net
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=school
      - DB_USERNAME=admin
      - DB_PASSWORD=saboor123
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=saboor123
      - MYSQL_DATABASE=school
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=saboor123
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mvc-net

volumes:
  mariadb_data:
networks:
  mvc-net:
